title: Project

files:
  sortable: true

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 2/4

  meta:
    label: Meta
    type:  text
    width: 2/4

  text:
    label: Text
    type:  textarea
